version: "3.4"
services:
  site:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - "./:/grav"
    command: "php -S 0.0.0.0:80 /grav/system/router.php"
    networks:
      - web
    labels:
      - traefik.enable=true
      - "traefik.http.routers.project.rule=Host(`project.grav`)"
      - "traefik.http.routers.api.entrypoints=http"
networks:
  web:
    external: true
